USE ODS;

DROP TABLE IF EXISTS TMP_DIRECCIONES_PRODUCTOS;
CREATE TABLE TMP_DIRECCIONES_PRODUCTOS AS
SELECT DIR.ID_DIRECCION
, DIR.DE_DIRECCION
, DIR.DE_CP
, CIU.DE_CIUDAD
, CIU.DE_ESTADO
, PAI.DE_PAIS
FROM ODS.ODS_HC_DIRECCIONES DIR
INNER JOIN ODS.ODS_DM_CIUDADES_ESTADOS CIU ON DIR.ID_CIUDAD_ESTADO=CIU.ID_CIUDAD_ESTADO
INNER JOIN ODS.ODS_DM_PAISES PAI ON CIU.ID_PAIS=PAI.ID_PAIS;

#Para optimizar el cruce entre ODS.TMP_DIRECCIONES_PRODUCTOS y STAGE.STG_PRODUCTOS_CRM
ALTER TABLE ODS.TMP_DIRECCIONES_PRODUCTOS ADD INDEX tmpdirprod_dir_idx (DE_DIRECCION ASC);
ALTER TABLE ODS.TMP_DIRECCIONES_PRODUCTOS ADD INDEX tmpdirprod_cp_idx (DE_CP ASC);
ALTER TABLE ODS.TMP_DIRECCIONES_PRODUCTOS ADD INDEX tmpdirprod_ciu_idx (DE_CIUDAD ASC);
ALTER TABLE ODS.TMP_DIRECCIONES_PRODUCTOS ADD INDEX tmpdirprod_est_idx (DE_ESTADO ASC);
ALTER TABLE ODS.TMP_DIRECCIONES_PRODUCTOS ADD INDEX tmpdirprod_pai_idx (DE_PAIS ASC);

ANALYZE TABLE TMP_DIRECCIONES_PRODUCTOS;
