USE ODS;

DROP TABLE IF EXISTS TMP_DIRECCIONES_PRODUCTOS;

CREATE TABLE TMP_DIRECCIONES_PRODUCTOS AS
SELECT DIR.ID_DIRECCION
, DIR.DE_DIRECCION
, DIR.DE_CP
, CIU.DE_CIUDAD
, CIU.DE_ESTADO
, PAI.DE_PAIS
FROM ODS.ODS_HC_DIRECCIONES DIR
INNER JOIN ODS.ODS_DM_CIUDADES_ESTADOS CIU ON DIR.ID_CIUDAD_ESTADO=CIU.ID_CIUDAD_ESTADO
INNER JOIN ODS.ODS_DM_PAISES PAI ON CIU.ID_PAIS=PAI.ID_PAIS;

#Para optimizar el cruce entre ODS.TMP_DIRECCIONES_PRODUCTOS y STAGE.STG_PRODUCTOS_CRM
ALTER TABLE ODS.TMP_DIRECCIONES_PRODUCTOS ADD INDEX tmpdirprod_dir_idx (DE_DIRECCION ASC);
ALTER TABLE ODS.TMP_DIRECCIONES_PRODUCTOS ADD INDEX tmpdirprod_cp_idx (DE_CP ASC);
ALTER TABLE ODS.TMP_DIRECCIONES_PRODUCTOS ADD INDEX tmpdirprod_ciu_idx (DE_CIUDAD ASC);
ALTER TABLE ODS.TMP_DIRECCIONES_PRODUCTOS ADD INDEX tmpdirprod_est_idx (DE_ESTADO ASC);
ALTER TABLE ODS.TMP_DIRECCIONES_PRODUCTOS ADD INDEX tmpdirprod_pai_idx (DE_PAIS ASC);

ANALYZE TABLE TMP_DIRECCIONES_PRODUCTOS;

DROP TABLE IF EXISTS TMP_DIRECCIONES_PRODUCTOS2;

CREATE TABLE TMP_DIRECCIONES_PRODUCTOS2 AS
SELECT PRODUCTOS.CUSTOMER_ID ID_CLIENTE, DIR.ID_DIRECCION
FROM STAGE.STG_PRODUCTOS_CRM PRODUCTOS
INNER JOIN ODS.TMP_DIRECCIONES_PRODUCTOS DIR ON CASE WHEN TRIM(PRODUCTOS.PRODUCT_ADDRESS)<>'' THEN UPPER(TRIM(PRODUCTOS.PRODUCT_ADDRESS)) ELSE 'DESCONOCIDO' END=DIR.DE_DIRECCION
		AND CASE WHEN TRIM(PRODUCTOS.PRODUCT_POSTAL_CODE)<>'' THEN TRIM(PRODUCTOS.PRODUCT_POSTAL_CODE) ELSE 99999 END=DIR.DE_CP
		AND CASE WHEN TRIM(PRODUCTOS.PRODUCT_CITY)<>'' THEN UPPER(TRIM(PRODUCTOS.PRODUCT_CITY)) ELSE 'DESCONOCIDO' END=DIR.DE_CIUDAD
		AND CASE WHEN TRIM(PRODUCTOS.PRODUCT_STATE)<>'' THEN UPPER(TRIM(PRODUCTOS.PRODUCT_STATE)) ELSE 'DESCONOCIDO' END=DIR.DE_ESTADO
		AND CASE 
			WHEN TRIM(PRODUCTOS.PRODUCT_COUNTRY)<>'' AND UPPER(TRIM(PRODUCTOS.PRODUCT_COUNTRY))='UNITED STATES' THEN 'US'
			WHEN TRIM(PRODUCTOS.PRODUCT_COUNTRY)<>'' THEN UPPER(TRIM(PRODUCTOS.PRODUCT_COUNTRY))
			ELSE 'DESCONOCIDO' END=DIR.DE_PAIS;

#Para optimizar el cruce entre ODS.TMP_DIRECCIONES_PRODUCTOS2 y STAGE.STG_PRODUCTOS_CRM
#ALTER TABLE ODS.TMP_DIRECCIONES_PRODUCTOS2 ADD INDEX tmpdirprod_idcli_idx (ID_CLIENTE ASC);

ANALYZE TABLE TMP_DIRECCIONES_PRODUCTOS2;

