USE ODS;

##########################################################################################################################

#========================================================================================================================#
# Insertar datos de Facturas
#========================================================================================================================#

INSERT INTO ODS_HC_FACTURAS
SELECT BILL_REF_NO AS ID_FACTURA
, CASE WHEN TRIM(CLI.ID_CLIENTE)<>'' THEN CLI.ID_CLIENTE ELSE 999999999 END ID_CLIENTE
, CASE WHEN TRIM(START_DATE)<>'' THEN STR_TO_DATE(START_DATE, '%Y-%m-%d %T') ELSE STR_TO_DATE('31/12/9999', '%d/%m/%Y %T') END FC_INICIO
, CASE WHEN TRIM(END_DATE)<>'' THEN STR_TO_DATE(END_DATE, '%Y-%m-%d %T') ELSE STR_TO_DATE('31/12/9999', '%d/%m/%Y %T') END FC_FIN
, CASE WHEN TRIM(STATEMENT_DATE)<>'' THEN STR_TO_DATE(STATEMENT_DATE, '%Y-%m-%d %T') ELSE STR_TO_DATE('31/12/9999', '%d/%m/%Y %T') END FC_ESTADO
, CASE WHEN TRIM(PAYMENT_DATE)<>'' THEN STR_TO_DATE(PAYMENT_DATE, '%Y-%m-%d %T') ELSE STR_TO_DATE('31/12/9999', '%d/%m/%Y %T') END FC_PAGO
, CASE WHEN TRIM(CIL.ID_CICLO_FACTURACION)<>'' THEN CIL.ID_CICLO_FACTURACION ELSE 999 END ID_CICLO_FACTURACION
, CASE WHEN TRIM(MET.ID_METODO_PAGO)<>'' THEN MET.ID_METODO_PAGO ELSE 999 END ID_METODO_PAGO
, AMOUNT AS CANTIDAD
, NOW()
, STR_TO_DATE('31/12/9999', '%d/%m/%Y %T')
FROM STAGE.STG_FACTURAS_FCT FACTURAS
INNER JOIN ODS.ODS_DM_CICLOS_FACTURACION CIL ON CASE WHEN TRIM(FACTURAS.BILL_CYCLE)<>'' THEN UPPER(TRIM(FACTURAS.BILL_CYCLE)) ELSE 'DESCONOCIDO' END=CIL.DE_CICLO_FACTURACION
INNER JOIN ODS.ODS_DM_METODOS_PAGO MET ON CASE WHEN TRIM(FACTURAS.BILL_METHOD)<>'' THEN UPPER(TRIM(FACTURAS.BILL_METHOD)) ELSE 'DESCONOCIDO' END=MET.DE_METODO_PAGO
LEFT OUTER JOIN ODS.ODS_HC_CLIENTES CLI ON CLI.ID_CLIENTE=FACTURAS.CUSTOMER_ID
;
COMMIT;

ANALYZE TABLE ODS_HC_FACTURAS;


#*************#
#*	PRUEBAS  *#
#*************#
/*
#BASE_ODS
SELECT DISTINCT FAC.ID_CLIENTE, CLI.* FROM BASE_ODS.ODS_HC_FACTURAS FAC 
INNER JOIN BASE_ODS.ODS_HC_CLIENTES CLI ON FAC.ID_CLIENTE = CLI.ID_CLIENTE
WHERE FAC.id_cliente > 99999999
ORDER BY FAC.id_cliente DESC
;
#---> Con Distinct: #2442
#---> Sin Distinct: #48840

#ODS
SELECT DISTINCT FAC.ID_CLIENTE, CLI.* FROM ODS.ODS_HC_FACTURAS FAC 
INNER JOIN ODS.ODS_HC_CLIENTES CLI ON FAC.ID_CLIENTE = CLI.ID_CLIENTE
WHERE FAC.id_cliente > 99999999
ORDER BY FAC.id_cliente DESC
#---> Con Distinct: #1
#---> Sin Distinct: #48840

## === 	SERVICIOS === ##
select count(*) from BASE_ODS.ODS_HC_SERVICIOS;	# 78495
select count(*) from ODS.ODS_HC_SERVICIOS;		# 78467
#---> Hay una diferencia de 28 registros originados en los clientes que existen 
#     en stg_productos_crm y no en stg_clientes_crm

SELECT * FROM BASE_ODS.ODS_HC_SERVICIOS SERV1
LEFT OUTER JOIN ODS.ODS_HC_SERVICIOS SERV2 ON SERV1.ID_SERVICIO = SERV2.ID_SERVICIO
WHERE SERV2.ID_SERVICIO IS NULL
;
*/