USE ODS;

INSERT INTO ODS_HC_DIRECCIONES (DE_DIRECCION, DE_CP, ID_CIUDAD_ESTADO, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(PRO.PRODUCT_ADDRESS)) DIRECCION
, CASE WHEN LENGTH(TRIM(PRO.PRODUCT_POSTAL_CODE))<>0 THEN TRIM(PRO.PRODUCT_POSTAL_CODE) ELSE 99999 END CP
, CIU.ID_CIUDAD_ESTADO
, NOW()
, NOW()
FROM STAGE.STG_PRODUCTOS_CRM PRO
INNER JOIN ODS.ODS_DM_PAISES PAI ON CASE 
	WHEN LENGTH(TRIM(PRO.PRODUCT_COUNTRY))<>0 AND UPPER(TRIM(PRO.PRODUCT_COUNTRY))='UNITED STATES' THEN 'US' #REPLACE(PRO.PRODUCT_COUNTRY, 'UNITED STATES', 'US')
	WHEN LENGTH(TRIM(PRO.PRODUCT_COUNTRY))<>0 THEN PRO.PRODUCT_COUNTRY 
ELSE 'DESCONOCIDO' END=PAI.DE_PAIS
INNER JOIN ODS.ODS_DM_CIUDADES_ESTADOS CIU ON CASE 
	WHEN LENGTH(TRIM(PRO.PRODUCT_CITY))<>0 THEN PRO.PRODUCT_CITY ELSE 'DESCONOCIDO' END=CIU.DE_CIUDAD
	AND CASE
    WHEN LENGTH(TRIM(PRO.PRODUCT_STATE))<>0 THEN PRO.PRODUCT_STATE ELSE 'DESCONOCIDO' END=CIU.DE_ESTADO
LEFT OUTER JOIN ODS.ODS_HC_DIRECCIONES DIR ON PRO.PRODUCT_ADDRESS = DIR.DE_DIRECCION AND PRO.PRODUCT_POSTAL_CODE = DIR.DE_CP
WHERE TRIM(PRODUCT_ADDRESS)<>'' AND (DIR.DE_DIRECCION IS NULL AND DIR.DE_CP IS NULL);

COMMIT;

ANALYZE TABLE ODS_HC_DIRECCIONES;
