USE ODS;

##########################################################################################################################

INSERT INTO ODS_DM_CANALES (DE_CANAL, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(CHANNEL)) CANAL, NOW(), NOW()
FROM STAGE.STG_PRODUCTOS_CRM
WHERE TRIM(CHANNEL)<>'';
# ---> 4 row(s) returned

COMMIT;

INSERT INTO ODS_DM_CANALES VALUES (999, 'DESCONOCIDO', NOW(), NOW());
INSERT INTO ODS_DM_CANALES VALUES (998, 'NO APLICA', NOW(), NOW());
COMMIT;
ANALYZE TABLE ODS_DM_CANALES;

##########################################################################################################################

INSERT INTO ODS_DM_PRODUCTOS (DE_PRODUCTO, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(PRODUCT_NAME)) PRODUCTO, NOW(), NOW()
FROM STAGE.STG_PRODUCTOS_CRM
WHERE TRIM(PRODUCT_NAME)<>'';
# ---> 6 row(s) returned

COMMIT;

INSERT INTO ODS_DM_PRODUCTOS VALUES (999, 'DESCONOCIDO', NOW(), NOW());
INSERT INTO ODS_DM_PRODUCTOS VALUES (998, 'NO APLICA', NOW(), NOW());
COMMIT;
ANALYZE TABLE ODS_DM_PRODUCTOS;

##########################################################################################################################

INSERT INTO ODS_DM_PAISES (DE_PAIS, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(PRODUCT_COUNTRY)) PAIS, NOW(), NOW()
FROM STAGE.STG_PRODUCTOS_CRM PRO
LEFT JOIN ODS.ODS_DM_PAISES PAI ON PRO.PRODUCT_COUNTRY=PAI.DE_PAIS
WHERE TRIM(PRODUCT_COUNTRY)<>'' AND UPPER(TRIM(PRODUCT_COUNTRY))<>'UNITED STATES';
COMMIT;

ANALYZE TABLE ODS_DM_PAISES;

##########################################################################################################################

INSERT INTO ODS_DM_CIUDADES_ESTADOS (DE_CIUDAD, DE_ESTADO, ID_PAIS, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(PRODUCT_CITY)) CIUDAD, UPPER(TRIM(PRODUCT_STATE)) ESTADO, UPPER(TRIM(PAI.ID_PAIS)) PAIS, NOW(), NOW()
FROM STAGE.STG_PRODUCTOS_CRM PRO
LEFT JOIN ODS.ODS_DM_PAISES PAI ON CASE 
	WHEN LENGTH(TRIM(PRO.PRODUCT_COUNTRY))<>0 AND UPPER(TRIM(PRO.PRODUCT_COUNTRY))='UNITED STATES' THEN 'US' #REPLACE(PRO.PRODUCT_COUNTRY, 'UNITED STATES', 'US')
    WHEN LENGTH(TRIM(PRO.PRODUCT_COUNTRY))<>0 THEN PRO.PRODUCT_COUNTRY
    ELSE 'DESCONOCIDO' 
    END=PAI.DE_PAIS

LEFT JOIN ODS.ODS_DM_CIUDADES_ESTADOS CIU ON CASE WHEN LENGTH(TRIM(PRO.PRODUCT_CITY))<>0 THEN PRO.PRODUCT_CITY ELSE 'DESCONOCIDO' END=CIU.DE_CIUDAD
 AND CASE WHEN LENGTH(TRIM(PRO.PRODUCT_STATE))<>0 THEN PRO.PRODUCT_STATE ELSE 'DESCONOCIDO' END=CIU.DE_ESTADO
 
WHERE CIU.DE_CIUDAD IS NULL AND CIU.DE_ESTADO IS NULL 
;

COMMIT;

ANALYZE TABLE ODS_DM_CIUDADES_ESTADOS;

##########################################################################################################################

