USE ODS;

DROP TABLE IF EXISTS ODS_HC_CLIENTES;
CREATE TABLE ODS_HC_CLIENTES
(ID_CLIENTE INT NOT NULL PRIMARY KEY
, NOMBRE_CLIENTE VARCHAR(512)
, APELLIDOS_CLIENTE VARCHAR(512)
, NUMDOC_CLIENTE VARCHAR(24)
, ID_SEXO INT(10) UNSIGNED
, ID_DIRECCION_CLIENTE INT(10) UNSIGNED
, TELEFONO_CLIENTE BIGINT
, EMAIL VARCHAR(512)
, FC_NACIMIENTO DATE
, ID_PROFESION INT(10) UNSIGNED
, ID_COMPANYA INT(10) UNSIGNED
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME
);

DROP TABLE IF EXISTS ODS_DM_SEXOS;
CREATE TABLE ODS_DM_SEXOS
(ID_SEXO INT UNSIGNED NOT NULL PRIMARY KEY
, DE_SEXO VARCHAR(64)
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME
);

DROP TABLE IF EXISTS ODS_DM_PROFESIONES;
CREATE TABLE ODS_DM_PROFESIONES
(ID_PROFESION INT UNSIGNED AUTO_INCREMENT PRIMARY KEY
, DE_PROFESION VARCHAR(512)
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME
);

DROP TABLE IF EXISTS ODS_DM_COMPANYAS;
CREATE TABLE ODS_DM_COMPANYAS
(ID_COMPANYA INT UNSIGNED AUTO_INCREMENT PRIMARY KEY
, DE_COMPANYA VARCHAR(512)
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME
);

DROP TABLE IF EXISTS ODS_HC_DIRECCIONES;
CREATE TABLE ODS_HC_DIRECCIONES
(ID_DIRECCION INT UNSIGNED AUTO_INCREMENT PRIMARY KEY
, DE_DIRECCION VARCHAR(512)
, DE_CP INT
, ID_CIUDAD_ESTADO INT(10) UNSIGNED
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME
);

DROP TABLE IF EXISTS ODS_DM_CIUDADES_ESTADOS;
CREATE TABLE ODS_DM_CIUDADES_ESTADOS
(ID_CIUDAD_ESTADO INT UNSIGNED AUTO_INCREMENT PRIMARY KEY
, DE_CIUDAD VARCHAR(512)
, DE_ESTADO VARCHAR(512)
, ID_PAIS INT(10) UNSIGNED
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME
);

DROP TABLE IF EXISTS ODS_DM_PAISES;
CREATE TABLE ODS_DM_PAISES
(ID_PAIS INT UNSIGNED AUTO_INCREMENT PRIMARY KEY
, DE_PAIS VARCHAR(512)
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME
);