USE ODS;

##########################################################################################################################

INSERT INTO ODS_DM_CANALES (DE_CANAL, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(CHANNEL)) CANAL, NOW(), NOW()
FROM STAGE.STG_PRODUCTOS_CRM
WHERE TRIM(CHANNEL)<>'';
# ---> 4 row(s) returned

COMMIT;

INSERT INTO ODS_DM_CANALES VALUES (999, 'DESCONOCIDO', NOW(), NOW());
INSERT INTO ODS_DM_CANALES VALUES (998, 'NO APLICA', NOW(), NOW());
COMMIT;
ANALYZE TABLE ODS_DM_CANALES;

##########################################################################################################################

INSERT INTO ODS_DM_PRODUCTOS (DE_PRODUCTO, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(PRODUCT_NAME)) PRODUCTO, NOW(), NOW()
FROM STAGE.STG_PRODUCTOS_CRM
WHERE TRIM(PRODUCT_NAME)<>'';
# ---> 6 row(s) returned

COMMIT;

INSERT INTO ODS_DM_PRODUCTOS VALUES (999, 'DESCONOCIDO', NOW(), NOW());
INSERT INTO ODS_DM_PRODUCTOS VALUES (998, 'NO APLICA', NOW(), NOW());
COMMIT;
ANALYZE TABLE ODS_DM_PRODUCTOS;


##########################################################################################################################

#========================================================================================================================#
## Para verificar el INSERT INTO ODS_DM_PAISES:
# Insertamos o modificamos un registro en STAGE.STG_PRODUCTOS_CRM con un valor de pais distinto a US para verificar que se 
# inserta en la tabla de paises ODS.ODS_DM_PAISES
#
UPDATE STAGE.STG_PRODUCTOS_CRM PROD
SET PROD.PRODUCT_COUNTRY = 'SPAIN', PROD.PRODUCT_CITY = 'MADRID', PROD.PRODUCT_STATE = 'COMUNIDAD MADRID'
WHERE PROD.PRODUCT_ID = '500001'
;
#
#SELECT * FROM STAGE.STG_PRODUCTOS_CRM PROD WHERE PROD.PRODUCT_ID = '500001';
#
# PRODUCT_ID, CUSTOMER_ID, PRODUCT_NAME, ACCESS_POINT, CHANNEL, AGENT_CODE, START_DATE, INSTALL_DATE, END_DATE, PRODUCT_CITY, PRODUCT_ADDRESS, PRODUCT_POSTAL_CODE, PRODUCT_STATE, PRODUCT_COUNTRY
#500001, 15862, Time-of-Use, 670920939964655837, Online, , 19/04/2006, 2006-05-02 22:47:41 UTC, 2006-09-16 22:47:41 UTC, Tucson, 2 Crescent Oaks Place, 85725, Arizona, United States
#
# Tambien podemos insertar directamente en ODS_DM_PAISES un registro de prueba: Esto no hace falta
#SELECT * FROM ODS.ODS_DM_PAISES;
#INSERT INTO ODS.ODS_DM_PAISES VALUES(555, 'UNITED STATES', NOW(), NOW());
#DELETE FROM ODS.ODS_DM_PAISES WHERE ID_PAIS = 555;
#========================================================================================================================#

#========================================================================================================================#
# Aqui dos pruebas para insertar en ODS_DM_PAISES valores nuevos de paises
# 'UNITED STATES' es un valor nuevo pero correponde con otro ya existente (US) por eso hay que evitar insertarlo.
#========================================================================================================================#
/* PRUEBA#1
INSERT INTO ODS_DM_PAISES (DE_PAIS, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(PRODUCT_COUNTRY)) PAIS, NOW(), NOW()
FROM STAGE.STG_PRODUCTOS_CRM PRO
LEFT JOIN ODS.ODS_DM_PAISES PAI ON PRO.PRODUCT_COUNTRY=PAI.DE_PAIS
WHERE TRIM(PRODUCT_COUNTRY)<>'';
*/
#---> Se insertara el registro UNITED STATES pero como ya existe un valor para el mismo pais (US) tenemos que controlar que no se incluya

/* PRUEBA#2
INSERT INTO ODS_DM_PAISES (DE_PAIS, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(PRODUCT_COUNTRY)) PAIS, NOW(), NOW()
FROM STAGE.STG_PRODUCTOS_CRM PRO
LEFT JOIN ODS.ODS_DM_PAISES PAI ON CASE
	#WHEN UPPER(TRIM(PRO.PRODUCT_COUNTRY))='UNITED STATES' THEN REPLACE(UPPER(TRIM(PRO.PRODUCT_COUNTRY)), 'UNITED STATES', 'US')
	WHEN UPPER(TRIM(PRO.PRODUCT_COUNTRY))='UNITED STATES' THEN 'SINONIMO'
	END=PAI.DE_PAIS
WHERE TRIM(PRODUCT_COUNTRY)<>'';
*/
#---> Esto no es valido: inserta igualmente 'UNITED STATES'

INSERT INTO ODS_DM_PAISES (DE_PAIS, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(PRODUCT_COUNTRY)) PAIS, NOW(), NOW()
FROM STAGE.STG_PRODUCTOS_CRM PRO
LEFT JOIN ODS.ODS_DM_PAISES PAI ON PRO.PRODUCT_COUNTRY=PAI.DE_PAIS
WHERE TRIM(PRODUCT_COUNTRY)<>'' AND UPPER(TRIM(PRODUCT_COUNTRY))<>'UNITED STATES';
COMMIT;

#========================================================================================================================#
# Estos valores ya existen en ODS_DM_PAISES
#========================================================================================================================#
#INSERT INTO ODS_DM_PAISES VALUES (99, 'DESCONOCIDO', NOW(), NOW());
#INSERT INTO ODS_DM_PAISES VALUES (98, 'NO APLICA', NOW(), NOW());
#COMMIT;

ANALYZE TABLE ODS_DM_PAISES;

##########################################################################################################################

#========================================================================================================================#
# Hay que cruzar con la tabla ODS_DM_PAISES y ODS_DM_CIUDADES_ESTADOS
#========================================================================================================================#
/* PRUEBA#1
INSERT INTO ODS_DM_CIUDADES_ESTADOS (DE_CIUDAD, DE_ESTADO, ID_PAIS, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(PRODUCT_CITY)) CIUDAD, UPPER(TRIM(PRODUCT_STATE)) ESTADO, PAI.ID_PAIS, NOW(), NOW()
FROM STAGE.STG_PRODUCTOS_CRM PRO
LEFT JOIN ODS.ODS_DM_PAISES PAI ON CASE
	WHEN LENGTH(TRIM(PRO.PRODUCT_COUNTRY))<>0 AND TRIM(PRO.PRODUCT_COUNTRY)='UNITED STATES' THEN 'US' #REPLACE(UPPER(TRIM(PRO.PRODUCT_COUNTRY)), 'UNITED STATES', 'US')
	WHEN LENGTH(TRIM(PRO.PRODUCT_COUNTRY))<>0 THEN PRO.PRODUCT_COUNTRY 
	ELSE 'DESCONOCIDO' 
	END=PAI.DE_PAIS
*/
#---> Esto no es valido porque inserta registros con (DE_CIUDAD, DE_ESTADO) ya existentes en la tabla ODS.ODS_DM_CIUDADES_ESTADOS
#	  No tenemos en cuenta los datos ya existentes en la tabla ODS.ODS_DM_CIUDADES_ESTADOS: se pueden repetir pares (DE_CIUDAD, DE_ESTADO)

/* PRUEBA#1_bis
INSERT INTO ODS_DM_CIUDADES_ESTADOS (DE_CIUDAD, DE_ESTADO, ID_PAIS, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(PRODUCT_CITY)) CIUDAD, UPPER(TRIM(PRODUCT_STATE)) ESTADO, PAI.ID_PAIS, NOW(), NOW()
FROM STAGE.STG_PRODUCTOS_CRM PRO
LEFT JOIN ODS.ODS_DM_PAISES PAI ON CASE
	WHEN LENGTH(TRIM(PRO.PRODUCT_COUNTRY))<>0 AND TRIM(PRO.PRODUCT_COUNTRY)='UNITED STATES' THEN 'US' #REPLACE(UPPER(TRIM(PRO.PRODUCT_COUNTRY)), 'UNITED STATES', 'US')
	WHEN LENGTH(TRIM(PRO.PRODUCT_COUNTRY))<>0 THEN PRO.PRODUCT_COUNTRY 
	ELSE 'DESCONOCIDO' 
	END=PAI.DE_PAIS
WHERE TRIM(PRODUCT_CITY)<>'' AND TRIM(PRODUCT_STATE)<>''
*/
#---> Es nuestro criterio decidir si los registros con PRODUCT_CITY y/o PRODUCT_STATE que sean nulos o vacios se descarten o no se incluyan.
#	  Es la misma consula que PRUEBA#1 pero sin considerar los registros que tengan PRODUCT_CITY y PRODUCT_STATE nulos o vacios.

/* PRUEBA#2
INSERT INTO ODS_DM_CIUDADES_ESTADOS (DE_CIUDAD, DE_ESTADO, ID_PAIS, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(PRODUCT_CITY)) CIUDAD, UPPER(TRIM(PRODUCT_STATE)) ESTADO, UPPER(TRIM(PAI.ID_PAIS)) PAIS, NOW(), NOW()
FROM STAGE.STG_PRODUCTOS_CRM PRO
LEFT JOIN ODS.ODS_DM_PAISES PAI ON CASE 
	WHEN LENGTH(TRIM(PRO.PRODUCT_COUNTRY))<>0 AND UPPER(TRIM(PRO.PRODUCT_COUNTRY))='UNITED STATES' THEN 'US'
    WHEN LENGTH(TRIM(PRO.PRODUCT_COUNTRY))<>0 THEN PRO.PRODUCT_COUNTRY
    ELSE 'DESCONOCIDO' 
    END=PAI.DE_PAIS
LEFT JOIN ODS.ODS_DM_CIUDADES_ESTADOS CIU ON PRO.PRODUCT_CITY = CIU.DE_CIUDAD AND PRO.PRODUCT_STATE = CIU.DE_ESTADO
WHERE CIU.DE_CIUDAD IS NULL AND CIU.DE_ESTADO IS NULL 
*/
#---> Consideramos los datos de la la tabla ODS.ODS_DM_CIUDADES_ESTADOS
#	  Se INCLUYEN registros con PRODUCT_CITY, PRODUCT_STATE e ID_PAIS nulos o vacios


/* PRUEBA#2_bis
INSERT INTO ODS_DM_CIUDADES_ESTADOS (DE_CIUDAD, DE_ESTADO, ID_PAIS, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(PRODUCT_CITY)) CIUDAD, UPPER(TRIM(PRODUCT_STATE)) ESTADO, UPPER(TRIM(PAI.ID_PAIS)) PAIS, NOW(), NOW()
FROM STAGE.STG_PRODUCTOS_CRM PRO
LEFT JOIN ODS.ODS_DM_PAISES PAI ON CASE 
	WHEN LENGTH(TRIM(PRO.PRODUCT_COUNTRY))<>0 AND UPPER(TRIM(PRO.PRODUCT_COUNTRY))='UNITED STATES' THEN 'US'
    WHEN LENGTH(TRIM(PRO.PRODUCT_COUNTRY))<>0 THEN PRO.PRODUCT_COUNTRY
    ELSE 'DESCONOCIDO' 
    END=PAI.DE_PAIS
LEFT JOIN ODS.ODS_DM_CIUDADES_ESTADOS CIU ON PRO.PRODUCT_CITY = CIU.DE_CIUDAD AND PRO.PRODUCT_STATE = CIU.DE_ESTADO
WHERE CIU.DE_CIUDAD IS NULL AND CIU.DE_ESTADO IS NULL 
GROUP BY PRODUCT_CITY, PRODUCT_STATE, PAI.ID_PAIS
HAVING PRODUCT_CITY<>'' AND PRODUCT_STATE<>'' AND PAI.ID_PAIS<>''
*/
#---> Consideramos los datos de la la tabla ODS.ODS_DM_CIUDADES_ESTADOS
#	  Se EXCLUEN registros con PRODUCT_CITY, PRODUCT_STATE e ID_PAIS nulos o vacios
#	  Con el registro de prueba obtenemos:
#	  #'MADRID', 'COMUNIDAD MADRID', NULL, '2017-12-08 21:45:35', '2017-12-08 21:45:35'

/* PRUEBA#3 */
/*
INSERT INTO ODS_DM_CIUDADES_ESTADOS (DE_CIUDAD, DE_ESTADO, ID_PAIS, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT
CASE WHEN TRIM(PRODUCT_CITY)<>'' THEN TRIM(UPPER(PRODUCT_CITY)) ELSE 'DESCONOCIDO' END CIUDAD
, CASE WHEN TRIM(PRODUCT_STATE)<>'' THEN TRIM(UPPER(PRODUCT_STATE)) ELSE 'DESCONOCIDO' END ESTADO
, UPPER(TRIM(PAI.ID_PAIS)) PAIS, NOW(), NOW()
FROM STAGE.STG_PRODUCTOS_CRM PRO
LEFT JOIN ODS.ODS_DM_PAISES PAI ON CASE 
	WHEN LENGTH(TRIM(PRO.PRODUCT_COUNTRY))<>0 AND UPPER(TRIM(PRO.PRODUCT_COUNTRY))='UNITED STATES' THEN 'US'
    WHEN LENGTH(TRIM(PRO.PRODUCT_COUNTRY))<>0 THEN PRO.PRODUCT_COUNTRY
    ELSE 'DESCONOCIDO' 
    END=PAI.DE_PAIS

LEFT JOIN ODS.ODS_DM_CIUDADES_ESTADOS CIU ON PRO.PRODUCT_CITY = CIU.DE_CIUDAD AND PRO.PRODUCT_STATE = CIU.DE_ESTADO
WHERE CIU.DE_CIUDAD IS NULL AND CIU.DE_ESTADO IS NULL 
;
#---> Consideramos los datos de la la tabla ODS.ODS_DM_CIUDADES_ESTADOS
#	  Vamos a considerar validos los registros con PRODUCT_CITY y PRODUCT_STATE nulos o vacios pero asignamos el valor 'DESCONOCIDO' a dichos campos.
#	  IMPORTANTE: si se vuelve a ejecutar esta query vuelve a insertar los registros que tengan PRODUCT_CITY y/o PRODUCT_STATE nulos o vacios

DELETE FROM ODS_DM_CIUDADES_ESTADOS WHERE DE_CIUDAD='DESCONOCIDO' AND DE_ESTADO='DESCONOCIDO' AND ID_CIUDAD_ESTADO <> 999
*/


/* FINAL - VERSION MEJORADA DE PRUEBA#3: NO ES NECESARIO REALIZAR EL DELETE */
INSERT INTO ODS_DM_CIUDADES_ESTADOS (DE_CIUDAD, DE_ESTADO, ID_PAIS, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(PRODUCT_CITY)) CIUDAD, UPPER(TRIM(PRODUCT_STATE)) ESTADO, UPPER(TRIM(PAI.ID_PAIS)) PAIS, NOW(), NOW()
FROM STAGE.STG_PRODUCTOS_CRM PRO
LEFT JOIN ODS.ODS_DM_PAISES PAI ON CASE 
	WHEN LENGTH(TRIM(PRO.PRODUCT_COUNTRY))<>0 AND UPPER(TRIM(PRO.PRODUCT_COUNTRY))='UNITED STATES' THEN 'US' #REPLACE(PRO.PRODUCT_COUNTRY, 'UNITED STATES', 'US')
    WHEN LENGTH(TRIM(PRO.PRODUCT_COUNTRY))<>0 THEN PRO.PRODUCT_COUNTRY
    ELSE 'DESCONOCIDO' 
    END=PAI.DE_PAIS

LEFT JOIN ODS.ODS_DM_CIUDADES_ESTADOS CIU ON CASE WHEN LENGTH(TRIM(PRO.PRODUCT_CITY))<>0 THEN PRO.PRODUCT_CITY ELSE 'DESCONOCIDO' END=CIU.DE_CIUDAD
 AND CASE WHEN LENGTH(TRIM(PRO.PRODUCT_STATE))<>0 THEN PRO.PRODUCT_STATE ELSE 'DESCONOCIDO' END=CIU.DE_ESTADO
 
WHERE CIU.DE_CIUDAD IS NULL AND CIU.DE_ESTADO IS NULL 
;

COMMIT;

#========================================================================================================================#
# Estos valores ya existen en ODS_DM_CIUDADES_ESTADOS
#========================================================================================================================#
#INSERT INTO ODS_DM_CIUDADES_ESTADOS VALUES (999, 'DESCONOCIDO', 'DESCONOCIDO', 99, NOW(), NOW());
#INSERT INTO ODS_DM_CIUDADES_ESTADOS VALUES (998, 'NO APLICA', 'NO APLICA', 98, NOW(), NOW());
#COMMIT;

ANALYZE TABLE ODS_DM_CIUDADES_ESTADOS;

##########################################################################################################################

