USE ODS;

ALTER TABLE ODS.ODS_HC_SERVICIOS ADD INDEX fk_ser_cli_idx (ID_CLIENTE ASC);
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD CONSTRAINT fk_ser_cli FOREIGN KEY (ID_CLIENTE) 
	REFERENCES ODS.ODS_HC_CLIENTES (ID_CLIENTE);

ALTER TABLE ODS.ODS_HC_SERVICIOS ADD INDEX fk_ser_dir_idx (ID_DIRECCION_SERVICIO ASC);
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD CONSTRAINT fk_ser_dir FOREIGN KEY (ID_DIRECCION_SERVICIO) 
	REFERENCES ODS.ODS_HC_DIRECCIONES (ID_DIRECCION);

ALTER TABLE ODS.ODS_HC_SERVICIOS ADD INDEX fk_ser_canal_idx (ID_CANAL ASC);
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD CONSTRAINT fk_ser_canal FOREIGN KEY (ID_CANAL) 
	REFERENCES ODS.ODS_DM_CANALES (ID_CANAL);

ALTER TABLE ODS.ODS_HC_SERVICIOS ADD INDEX fk_ser_prod_idx (ID_PRODUCTO ASC);
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD CONSTRAINT fk_ser_prod FOREIGN KEY (ID_PRODUCTO) 
	REFERENCES ODS.ODS_DM_PRODUCTOS (ID_PRODUCTO);

# Para optimizar el cruce para ODS_HC_DIRECCIONES
ALTER TABLE ODS.ODS_HC_DIRECCIONES ADD INDEX dir_dir_idx (DE_DIRECCION ASC);
ALTER TABLE ODS.ODS_HC_DIRECCIONES ADD INDEX dir_cp_idx (DE_CP ASC);
ALTER TABLE STAGE.STG_PRODUCTOS_CRM ADD INDEX pro_add_idx(PRODUCT_ADDRESS ASC);
ALTER TABLE STAGE.STG_PRODUCTOS_CRM ADD INDEX pro_cp_idx(PRODUCT_POSTAL_CODE ASC);