USE ODS;

DROP TABLE IF EXISTS TMP_DIRECCIONES_CLIENTES;

CREATE TABLE TMP_DIRECCIONES_CLIENTES AS
SELECT DIR.ID_DIRECCION
, DIR.DE_DIRECCION
, DIR.DE_CP
, CIU.DE_CIUDAD
, CIU.DE_ESTADO
, PAI.DE_PAIS
FROM ODS.ODS_HC_DIRECCIONES DIR
INNER JOIN ODS.ODS_DM_CIUDADES_ESTADOS CIU ON DIR.ID_CIUDAD_ESTADO=CIU.ID_CIUDAD_ESTADO
INNER JOIN ODS.ODS_DM_PAISES PAI ON CIU.ID_PAIS=PAI.ID_PAIS;

ANALYZE TABLE TMP_DIRECCIONES_CLIENTES;

DROP TABLE IF EXISTS TMP_DIRECCIONES_CLIENTES2;

CREATE TABLE TMP_DIRECCIONES_CLIENTES2 AS
SELECT CLIENTES.CUSTOMER_ID ID_CLIENTE, DIR.ID_DIRECCION
FROM STAGE.STG_CLIENTES_CRM CLIENTES
INNER JOIN ODS.TMP_DIRECCIONES_CLIENTES DIR ON CASE WHEN TRIM(CLIENTES.ADDRESS)<>'' THEN UPPER(TRIM(CLIENTES.ADDRESS)) ELSE 'DESCONOCIDO' END=DIR.DE_DIRECCION
		AND CASE WHEN TRIM(CLIENTES.POSTAL_CODE)<>'' THEN TRIM(CLIENTES.POSTAL_CODE) ELSE 99999 END=DIR.DE_CP
		AND CASE WHEN TRIM(CLIENTES.CITY)<>'' THEN UPPER(TRIM(CLIENTES.CITY)) ELSE 'DESCONOCIDO' END=DIR.DE_CIUDAD
		AND CASE WHEN TRIM(CLIENTES.STATE)<>'' THEN UPPER(TRIM(CLIENTES.STATE)) ELSE 'DESCONOCIDO' END=DIR.DE_ESTADO
		AND CASE WHEN TRIM(CLIENTES.COUNTRY)<>'' THEN UPPER(TRIM(CLIENTES.COUNTRY)) ELSE 'DESCONOCIDO' END=DIR.DE_PAIS;

ANALYZE TABLE TMP_DIRECCIONES_CLIENTES2;