USE ODS;

INSERT INTO ODS_HC_CLIENTES
SELECT CUSTOMER_ID AS ID_CLIENTE
, CASE WHEN TRIM(FIRST_NAME)<>'' THEN TRIM(UPPER(FIRST_NAME)) ELSE 'DESCONOCIDO' END NOMBRE_CLIENTE
, CASE WHEN TRIM(LAST_NAME)<>'' THEN TRIM(UPPER(LAST_NAME)) ELSE 'DESCONOCIDO' END APELLIDOS_CLIENTE
, CASE WHEN TRIM(IDENTIFIED_DOC)<>'' THEN TRIM(UPPER(IDENTIFIED_DOC)) ELSE '99-999-9999' END NUMDOC_CLIENTE
, SEXO.ID_SEXO
, CASE WHEN TRIM(DIR.ID_DIRECCION)<>'' THEN DIR.ID_DIRECCION ELSE 999999 END ID_DIRECCION
, CASE WHEN TRIM(PHONE)<>'' THEN REPLACE(PHONE,'-','') ELSE 9999999999 END TELEFONO_CLIENTE
, CASE WHEN TRIM(EMAIL)<>'' THEN TRIM(UPPER(EMAIL)) ELSE 'DESCONOCIDO' END EMAIL
, CASE WHEN TRIM(BIRTHDAY)<>'' THEN STR_TO_DATE(BIRTHDAY, '%d/%m/%Y %T') ELSE STR_TO_DATE('31/12/9999', '%d/%m/%Y %T') END FC_NACIMIENTO
, PROF.ID_PROFESION
, COMP.ID_COMPANYA
, NOW()
, STR_TO_DATE('31/12/9999', '%d/%m/%Y %T')
FROM STAGE.STG_CLIENTES_CRM CLIENTES
INNER JOIN ODS.ODS_DM_SEXOS SEXO ON CASE WHEN TRIM(CLIENTES.GENDER)<>'' THEN UPPER(TRIM(CLIENTES.GENDER)) ELSE 'DESCONOCIDO' END=SEXO.DE_SEXO
INNER JOIN ODS.ODS_DM_PROFESIONES PROF ON CASE WHEN TRIM(CLIENTES.PROFESION)<>'' THEN UPPER(TRIM(CLIENTES.PROFESION)) ELSE 'NO APLICA' END=PROF.DE_PROFESION
INNER JOIN ODS.ODS_DM_COMPANYAS COMP ON CASE WHEN TRIM(CLIENTES.COMPANY)<>'' THEN UPPER(TRIM(CLIENTES.COMPANY)) ELSE 'DESCONOCIDO' END=COMP.DE_COMPANYA
LEFT OUTER JOIN ODS.TMP_DIRECCIONES_CLIENTES2 DIR ON CLIENTES.CUSTOMER_ID=DIR.ID_CLIENTE
;
COMMIT;

#*************************#
#*  CLIENTE DESCONOCIDO  *#
#*************************#
INSERT INTO ODS_HC_CLIENTES VALUES (999999999, 'DESCONOCIDO', 'DESCONOCIDO', '99-999-9999', 99, 999999, 9999999999
, 'DESCONOCIDO', STR_TO_DATE('31/12/9999', '%d/%m/%Y %T'), 999, 999, NOW(), STR_TO_DATE('31/12/9999', '%d/%m/%Y %T'));
COMMIT;

ANALYZE TABLE ODS_HC_CLIENTES;

#DROP TABLE IF EXISTS TMP_DIRECCIONES_CLIENTES;
#DROP TABLE IF EXISTS TMP_DIRECCIONES_CLIENTES2;