USE ODS;

##########################################################################################################################

#========================================================================================================================#
# Insertar datos de Servicios/Productos
#========================================================================================================================#

/************************************************************************************************************************
* Para parser las fechas UTC se puede aplicar un SUBSTR();
* , CASE WHEN TRIM(INSTALL_DATE)<>'' AND UPPER(INSTALL_DATE) LIKE '%UTC' THEN SUBSTR(INSTALL_DATE, 1, 19) ELSE STR_TO_DATE('31/12/9999', '%d/%m/%Y') END FC_INSTALACION
* , CASE WHEN TRIM(END_DATE)<>'' AND UPPER(END_DATE) LIKE '%UTC' THEN SUBSTR(END_DATE, 1, 19) ELSE STR_TO_DATE('31/12/9999', '%d/%m/%Y') END FC_FIN
* 
* o preferiblemente un REPLACE()
* , CASE WHEN TRIM(INSTALL_DATE)<>'' AND UPPER(INSTALL_DATE) LIKE '%UTC' THEN REPLACE(UPPER(TRIM(INSTALL_DATE)), 'UTC', '') ELSE STR_TO_DATE('31/12/9999', '%d/%m/%Y') END FC_INSTALACION
* , CASE WHEN TRIM(END_DATE)<>'' AND UPPER(END_DATE) LIKE '%UTC' THEN REPLACE(UPPER(TRIM(END_DATE)), 'UTC', '') ELSE STR_TO_DATE('31/12/9999', '%d/%m/%Y') END FC_FIN
*/

/*
INSERT INTO ODS_HC_SERVICIOS
SELECT PRODUCT_ID AS ID_SERVICIO
, CUSTOMER_ID AS ID_CLIENTE
, CASE WHEN TRIM(PRO.ID_PRODUCTO) THEN PRO.ID_PRODUCTO ELSE 999 END ID_PRODUCTO
, ACCESS_POINT AS PUNTO_ACCESO
, CASE WHEN TRIM(CAN.ID_CANAL)<>'' THEN CAN.ID_CANAL ELSE 999 END ID_CANAL
, CASE WHEN TRIM(AGENT_CODE)<>'' THEN  CAST(AGENT_CODE AS UNSIGNED INT) ELSE 99999 END ID_AGENTE
, CASE WHEN TRIM(DIR.ID_DIRECCION)<>'' THEN DIR.ID_DIRECCION ELSE 999999 END ID_DIRECCION_SERVICIO
, CASE WHEN TRIM(START_DATE)<>'' THEN STR_TO_DATE(START_DATE, '%d/%m/%Y %T') ELSE STR_TO_DATE('31/12/9999', '%d/%m/%Y %T') END FC_INICIO
, CASE WHEN TRIM(INSTALL_DATE)<>'' AND UPPER(INSTALL_DATE) LIKE '%UTC' THEN REPLACE(UPPER(TRIM(INSTALL_DATE)), 'UTC', '') ELSE STR_TO_DATE('31/12/9999', '%d/%m/%Y %T') END FC_INSTALACION
, CASE WHEN TRIM(END_DATE)<>'' AND UPPER(END_DATE) LIKE '%UTC' THEN REPLACE(UPPER(TRIM(END_DATE)), 'UTC', '') ELSE STR_TO_DATE('31/12/9999', '%d/%m/%Y %T') END FC_FIN
, NOW()
, STR_TO_DATE('31/12/9999', '%d/%m/%Y %T')
FROM STAGE.STG_PRODUCTOS_CRM PRODUCTOS
INNER JOIN ODS.ODS_DM_PRODUCTOS PRO ON CASE WHEN TRIM(PRODUCTOS.PRODUCT_NAME)<>'' THEN UPPER(TRIM(PRODUCTOS.PRODUCT_NAME)) ELSE 'DESCONOCIDO' END=PRO.DE_PRODUCTO
INNER JOIN ODS.ODS_DM_CANALES CAN ON CASE WHEN TRIM(PRODUCTOS.CHANNEL)<>'' THEN UPPER(TRIM(PRODUCTOS.CHANNEL)) ELSE 'DESCONOCIDO' END=CAN.DE_CANAL
LEFT OUTER JOIN ODS.TMP_DIRECCIONES_PRODUCTOS2 DIR ON PRODUCTOS.CUSTOMER_ID=DIR.ID_CLIENTE
;
*/
INSERT INTO ODS_HC_SERVICIOS
SELECT PRODUCT_ID AS ID_SERVICIO
, CUSTOMER_ID AS ID_CLIENTE
, CASE WHEN TRIM(PRO.ID_PRODUCTO)<>'' THEN PRO.ID_PRODUCTO ELSE 999 END ID_PRODUCTO
, ACCESS_POINT AS PUNTO_ACCESO
, CASE WHEN TRIM(CAN.ID_CANAL)<>'' THEN CAN.ID_CANAL ELSE 999 END ID_CANAL
, CASE WHEN TRIM(AGENT_CODE)<>'' THEN  CAST(AGENT_CODE AS UNSIGNED INT) ELSE 99999 END ID_AGENTE
, CASE WHEN TRIM(DIR.ID_DIRECCION)<>'' THEN DIR.ID_DIRECCION ELSE 999999 END ID_DIRECCION_SERVICIO
, CASE WHEN TRIM(START_DATE)<>'' THEN STR_TO_DATE(START_DATE, '%d/%m/%Y %T') ELSE STR_TO_DATE('31/12/9999', '%d/%m/%Y %T') END FC_INICIO
, CASE WHEN TRIM(INSTALL_DATE)<>'' AND UPPER(INSTALL_DATE) LIKE '%UTC' THEN REPLACE(UPPER(TRIM(INSTALL_DATE)), 'UTC', '') ELSE STR_TO_DATE('31/12/9999', '%d/%m/%Y %T') END FC_INSTALACION
, CASE WHEN TRIM(END_DATE)<>'' AND UPPER(END_DATE) LIKE '%UTC' THEN REPLACE(UPPER(TRIM(END_DATE)), 'UTC', '') ELSE STR_TO_DATE('31/12/9999', '%d/%m/%Y %T') END FC_FIN
, NOW()
, STR_TO_DATE('31/12/9999', '%d/%m/%Y %T')
FROM STAGE.STG_PRODUCTOS_CRM PRODUCTOS
INNER JOIN ODS.ODS_DM_PRODUCTOS PRO ON CASE WHEN TRIM(PRODUCTOS.PRODUCT_NAME)<>'' THEN UPPER(TRIM(PRODUCTOS.PRODUCT_NAME)) ELSE 'DESCONOCIDO' END=PRO.DE_PRODUCTO
INNER JOIN ODS.ODS_DM_CANALES CAN ON CASE WHEN TRIM(PRODUCTOS.CHANNEL)<>'' THEN UPPER(TRIM(PRODUCTOS.CHANNEL)) ELSE 'DESCONOCIDO' END=CAN.DE_CANAL
INNER JOIN ODS.ODS_HC_CLIENTES CLI ON CASE WHEN TRIM(PRODUCTOS.CUSTOMER_ID)<>'' THEN CAST(TRIM(PRODUCTOS.CUSTOMER_ID) AS UNSIGNED) ELSE 999999999 END= CLI.ID_CLIENTE
LEFT OUTER JOIN ODS.TMP_DIRECCIONES_PRODUCTOS DIR ON CASE WHEN TRIM(PRODUCTOS.PRODUCT_ADDRESS)<>'' THEN UPPER(TRIM(PRODUCTOS.PRODUCT_ADDRESS)) ELSE 'DESCONOCIDO' END=DIR.DE_DIRECCION
		AND CASE WHEN TRIM(PRODUCTOS.PRODUCT_POSTAL_CODE)<>'' THEN TRIM(PRODUCTOS.PRODUCT_POSTAL_CODE) ELSE 99999 END=DIR.DE_CP
		AND CASE WHEN TRIM(PRODUCTOS.PRODUCT_CITY)<>'' THEN UPPER(TRIM(PRODUCTOS.PRODUCT_CITY)) ELSE 'DESCONOCIDO' END=DIR.DE_CIUDAD
		AND CASE WHEN TRIM(PRODUCTOS.PRODUCT_STATE)<>'' THEN UPPER(TRIM(PRODUCTOS.PRODUCT_STATE)) ELSE 'DESCONOCIDO' END=DIR.DE_ESTADO
		AND CASE 
			WHEN TRIM(PRODUCTOS.PRODUCT_COUNTRY)<>'' AND UPPER(TRIM(PRODUCTOS.PRODUCT_COUNTRY))='UNITED STATES' THEN 'US'
			WHEN TRIM(PRODUCTOS.PRODUCT_COUNTRY)<>'' THEN UPPER(TRIM(PRODUCTOS.PRODUCT_COUNTRY))
			ELSE 'DESCONOCIDO' END=DIR.DE_PAIS
;
COMMIT;

ANALYZE TABLE ODS_HC_SERVICIOS;

#DROP TABLE IF EXISTS TMP_DIRECCIONES_PRODUCTOS;
#DROP TABLE IF EXISTS TMP_DIRECCIONES_PRODUCTOS2;

