USE ODS;

##########################################################################################################################

#========================================================================================================================#
# Insertar datos de Llamadas
#========================================================================================================================#

INSERT INTO ODS_HC_LLAMADAS (ID_IVR, TELEFONO_LLAMADA, ID_CLIENTE, FC_INICIO_LLAMADA, FC_FIN_LLAMADA, ID_DEPARTAMENTO_CC, FLG_TRANSFERIDO, ID_AGENTE_CC, FC_INSERT, FC_MODIFICACION)
SELECT ID AS ID_IVR
, CASE WHEN LENGTH(TRIM(PHONE_NUMBER))=10 THEN CAST(PHONE_NUMBER AS UNSIGNED INT) ELSE 9999999999 END TELEFONO_LLAMADA
, CASE WHEN TRIM(CLI.ID_CLIENTE)<>'' THEN CLI.ID_CLIENTE ELSE 999999999 END ID_CLIENTE
, CASE WHEN LENGTH(TRIM(START_DATETIME))<>0 THEN STR_TO_DATE(START_DATETIME, '%Y-%m-%d %T.%f') ELSE STR_TO_DATE('31/12/9999', '%d/%m/%Y %T') END FC_INICIO_LLAMADA
, CASE WHEN LENGTH(TRIM(END_DATETIME))<>0 THEN STR_TO_DATE(END_DATETIME, '%Y-%m-%d %T.%f') ELSE STR_TO_DATE('31/12/9999', '%d/%m/%Y %T') END FC_FIN_LLAMADA
, CASE WHEN TRIM(DEP.ID_DEPARTAMENTO_CC)<>'' THEN DEP.ID_DEPARTAMENTO_CC ELSE 999 END ID_DEPARTAMENTO_CC
, CASE WHEN UPPER(TRIM(LLAMADAS.FLG_TRANSFER))='TRUE' THEN 1 ELSE 0 END FLG_TRANSFERIDO
, CASE WHEN TRIM(AGEN.ID_AGENTE_CC)<>'' THEN AGEN.ID_AGENTE_CC ELSE 99999 END ID_AGENTE_CC
, NOW()
, STR_TO_DATE('31/12/9999', '%d/%m/%Y %T')
FROM STAGE.STG_CONTACTOS_IVR LLAMADAS
INNER JOIN ODS.ODS_DM_DEPARTAMENTOS_CC DEP ON CASE WHEN TRIM(LLAMADAS.SERVICE)<>'' THEN UPPER(TRIM(LLAMADAS.SERVICE)) ELSE 'DESCONOCIDO' END=DEP.DE_DEPARTAMENTO_CC
INNER JOIN ODS.ODS_DM_AGENTES_CC AGEN ON CASE WHEN TRIM(LLAMADAS.AGENT)<>'' THEN UPPER(TRIM(LLAMADAS.AGENT)) ELSE 'DESCONOCIDO' END=AGEN.DE_AGENTE_CC
LEFT OUTER JOIN ODS.ODS_HC_CLIENTES CLI ON CLI.TELEFONO_CLIENTE=LLAMADAS.PHONE_NUMBER
;
COMMIT;

ANALYZE TABLE ODS_HC_LLAMADAS;
