USE STAGE;

SELECT COUNT(*) TOTAL_REGISTROS
, SUM(CASE WHEN LENGTH(TRIM(BILL_REF_NO))<>0 THEN 1 ELSE 0 END) TOTAL_BILL_REF_NO
, SUM(CASE WHEN LENGTH(TRIM(BILL_REF_NO))=0 OR BILL_REF_NO IS NULL THEN 1 ELSE 0 END) TOTAL_NULOSVACIOS_BILL_REF_NO
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(BILL_REF_NO))<>0 THEN BILL_REF_NO ELSE 0 END) TOTAL_DISTINTOS_BILL_REF_NO

, SUM(CASE WHEN LENGTH(TRIM(CUSTOMER_ID))<>0 THEN 1 ELSE 0 END) TOTAL_CUSTOMER_ID
, SUM(CASE WHEN LENGTH(TRIM(CUSTOMER_ID))=0 OR CUSTOMER_ID IS NULL THEN 1 ELSE 0 END) TOTAL_NULOSVACIOS_CUSTOMER_ID
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(CUSTOMER_ID))<>0 THEN CUSTOMER_ID ELSE 0 END) TOTAL_DISTINTOS_CUSTOMER_ID

, SUM(CASE WHEN LENGTH(TRIM(START_DATE))<>0 THEN 1 ELSE 0 END) TOTAL_START_DATE
, SUM(CASE WHEN LENGTH(TRIM(START_DATE))=0 OR START_DATE IS NULL THEN 1 ELSE 0 END) TOTAL_NULOSVACIOS_START_DATE
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(START_DATE))<>0 THEN START_DATE ELSE 0 END) TOTAL_DISTINTOS_START_DATE

, SUM(CASE WHEN LENGTH(TRIM(END_DATE))<>0 THEN 1 ELSE 0 END) TOTAL_END_DATE
, SUM(CASE WHEN LENGTH(TRIM(END_DATE))=0 OR END_DATE IS NULL THEN 1 ELSE 0 END) TOTAL_NULOSVACIOS_END_DATE
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(END_DATE))<>0 THEN END_DATE ELSE 0 END) TOTAL_DISTINTOS_END_DATE

, SUM(CASE WHEN LENGTH(TRIM(STATEMENT_DATE))<>0 THEN 1 ELSE 0 END) TOTAL_STATEMENT_DATE
, SUM(CASE WHEN LENGTH(TRIM(STATEMENT_DATE))=0 OR STATEMENT_DATE IS NULL THEN 1 ELSE 0 END) TOTAL_NULOSVACIOS_STATEMENT_DATE
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(STATEMENT_DATE))<>0 THEN STATEMENT_DATE ELSE 0 END) TOTAL_DISTINTOS_STATEMENT_DATE

, SUM(CASE WHEN LENGTH(TRIM(PAYMENT_DATE))<>0 THEN 1 ELSE 0 END) TOTAL_PAYMENT_DATE
, SUM(CASE WHEN LENGTH(TRIM(PAYMENT_DATE))=0 OR PAYMENT_DATE IS NULL THEN 1 ELSE 0 END) TOTAL_NULOSVACIOS_PAYMENT_DATE
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(PAYMENT_DATE))<>0 THEN PAYMENT_DATE ELSE 0 END) TOTAL_DISTINTOS_PAYMENT_DATE

, SUM(CASE WHEN LENGTH(TRIM(BILL_CYCLE))<>0 THEN 1 ELSE 0 END) TOTAL_BILL_CYCLE
, SUM(CASE WHEN LENGTH(TRIM(BILL_CYCLE))=0 OR BILL_CYCLE IS NULL THEN 1 ELSE 0 END) TOTAL_NULOSVACIOS_BILL_CYCLE
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(BILL_CYCLE))<>0 THEN BILL_CYCLE ELSE 0 END) TOTAL_DISTINTOS_BILL_CYCLE

, SUM(CASE WHEN LENGTH(TRIM(AMOUNT))<>0 THEN 1 ELSE 0 END) TOTAL_AMOUNT
, SUM(CASE WHEN LENGTH(TRIM(AMOUNT))=0 OR AMOUNT IS NULL THEN 1 ELSE 0 END) TOTAL_NULOSVACIOS_AMOUNT
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(AMOUNT))<>0 THEN AMOUNT ELSE 0 END) TOTAL_DISTINTOS_AMOUNT

, SUM(CASE WHEN LENGTH(TRIM(BILL_METHOD))<>0 THEN 1 ELSE 0 END) TOTAL_BILL_METHOD
, SUM(CASE WHEN LENGTH(TRIM(BILL_METHOD))=0 OR BILL_METHOD IS NULL THEN 1 ELSE 0 END) TOTAL_NULOSVACIOS_BILL_METHOD
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(BILL_METHOD))<>0 THEN BILL_METHOD ELSE 0 END) TOTAL_DISTINTOS_BILL_METHOD

FROM STAGE.STG_FACTURAS_FCT;