USE STAGE;

#Para optimizar el cruce entre ODS.ODS_HC_CLIENTES y STAGE.STG_CONTACTOS_IVR
ALTER TABLE STAGE.STG_CONTACTOS_IVR ADD INDEX ivr_tel_idx (PHONE_NUMBER ASC);
ALTER TABLE STAGE.STG_CLIENTES_CRM ADD INDEX cli_tel_idx (PHONE ASC);
