USE STAGE;

SELECT COUNT(*) TOTAL_REGISTROS
, SUM(CASE WHEN LENGTH(TRIM(ID))<>0 THEN 1 ELSE 0 END) TOTAL_ID
, SUM(CASE WHEN LENGTH(TRIM(ID))=0 OR ID IS NULL THEN 1 ELSE 0 END) TOTAL_NULOSVACIOS_ID
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(ID))<>0 THEN ID ELSE 0 END) TOTAL_DISTINTOS_ID

, SUM(CASE WHEN LENGTH(TRIM(`ORDER`))<>0 THEN 1 ELSE 0 END) TOTAL_ORDER
, SUM(CASE WHEN LENGTH(TRIM(`ORDER`))=0 OR `ORDER` IS NULL THEN 1 ELSE 0 END) TOTAL_NULOSVACIOS_ORDER
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(`ORDER`))<>0 THEN `ORDER` ELSE 0 END) TOTAL_DISTINTOS_ORDER

, SUM(CASE WHEN LENGTH(TRIM(PHASE))<>0 THEN 1 ELSE 0 END) TOTAL_PHASE
, SUM(CASE WHEN LENGTH(TRIM(PHASE))=0 OR PHASE IS NULL THEN 1 ELSE 0 END) TOTAL_NULOSVACIOS_PHASE
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(PHASE))<>0 THEN PHASE ELSE 0 END) TOTAL_DISTINTOS_PHASE

, SUM(CASE WHEN LENGTH(TRIM(AGENT))<>0 THEN 1 ELSE 0 END) TOTAL_AGENT
, SUM(CASE WHEN LENGTH(TRIM(AGENT))=0 OR AGENT IS NULL THEN 1 ELSE 0 END) TOTAL_NULOSVACIOS_AGENT
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(AGENT))<>0 THEN AGENT ELSE 0 END) TOTAL_DISTINTOS_AGENT

, SUM(CASE WHEN LENGTH(TRIM(START_DT))<>0 THEN 1 ELSE 0 END) TOTAL_START_DT
, SUM(CASE WHEN LENGTH(TRIM(START_DT))=0 OR START_DT IS NULL THEN 1 ELSE 0 END) TOTAL_NULOSVACIOS_START_DT
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(START_DT))<>0 THEN START_DT ELSE 0 END) TOTAL_DISTINTOS_START_DT

, SUM(CASE WHEN LENGTH(TRIM(END_DT))<>0 THEN 1 ELSE 0 END) TOTAL_END_DT
, SUM(CASE WHEN LENGTH(TRIM(END_DT))=0 OR END_DT IS NULL THEN 1 ELSE 0 END) TOTAL_NULOSVACIOS_END_DT
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(END_DT))<>0 THEN END_DT ELSE 0 END) TOTAL_DISTINTOS_END_DT

FROM STAGE.STG_ORDERS_CRM;