USE STAGE;

DROP TABLE IF EXISTS STG_CLIENTES_CRM;
CREATE TABLE STG_CLIENTES_CRM AS SELECT * FROM CRM.CLIENTES;
ANALYZE TABLE STG_CLIENTES_CRM;

DROP TABLE IF EXISTS STG_ORDERS_CRM;
CREATE TABLE STG_ORDERS_CRM AS SELECT * FROM CRM.ORDERS;
ANALYZE TABLE STG_ORDERS_CRM;

DROP TABLE IF EXISTS STG_PRODUCTOS_CRM;
CREATE TABLE STG_PRODUCTOS_CRM AS SELECT * FROM CRM.PRODUCTOS;
ANALYZE TABLE STG_PRODUCTOS_CRM;

DROP TABLE IF EXISTS STG_FACTURAS_FCT;
CREATE TABLE STG_FACTURAS_FCT AS SELECT * FROM FACTURADOR.FACTURAS;
ANALYZE TABLE STG_FACTURAS_FCT;

DROP TABLE IF EXISTS STG_CONTACTOS_IVR;
CREATE TABLE STG_CONTACTOS_IVR AS SELECT * FROM IVR.CONTACTOS;
ANALYZE TABLE STG_CONTACTOS_IVR;
